[broker]
socket_dir = "/run/vmshm"

# object/data shared window
[[domains]]
id = "vmshm-object"
socket_path = "/run/vmshm/vmshm-object.sock"
memfd_name = "vmshm-object"
window_size = 67108864
seal = true

# control/rpc shared window
[[domains]]
id = "vmshm-comm"
socket_path = "/run/vmshm/vmshm-comm.sock"
memfd_name = "vmshm-comm"
window_size = 33554432
seal = true
